version: '3.8'

services:
  app:
    build: .
    container_name: blog_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_LOG_DIR=/code/logs
    volumes:
      - ./logs/app:/code/logs
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: blog_db
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    command: [
      "postgres",
      "-c", "logging_collector=on",
      "-c", "log_directory=/var/log/postgresql",
      "-c", "log_filename=postgresql-%a.log",
      "-c", "log_truncate_on_rotation=on",
      "-c", "log_rotation_age=1d",
      "-c", "log_rotation_size=0"
    ]
    restart: unless-stopped
